/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_shop;
import backend.customerBackend;
import backend.orderBackend;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.concurrent.*;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import types.employee;
import types.order;
import utils.customHooks;
import javax.swing.SwingUtilities;
/**
 *
 * @author U
 */
public class customerOrders extends javax.swing.JFrame {
    private employee myEmployee;
    private orderBackend orderClass = new orderBackend();
    private customerBackend customerBackend = new customerBackend();
    /**
     * Creates new form customerOrders
     */
    public customerOrders() {
        initComponents();
        customHooks.changeFrame1(this, new landingPage());
        ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
            
        scheduler.scheduleAtFixedRate(() -> {
            ArrayList<order> orders = orderClass.getOrders("serving", "to claim");

            SwingUtilities.invokeLater(() -> { // Ensures UI updates happen on the Event Dispatch Thread
                orderContainer.removeAll(); // Clear old components
                orderContainer.setLayout(new GridLayout(0, 1, 15, 15)); 
                orderContainer.setBackground(new Color(230, 230, 230)); 

               

                for (order currrentOrder : orders) {
                    JPanel productPanel = new JPanel();
                    productPanel.setLayout(new BoxLayout(productPanel, BoxLayout.Y_AXIS));
                    productPanel.setPreferredSize(new Dimension(200, 90));
                    productPanel.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createLineBorder(new Color(180, 180, 180), 2),
                        BorderFactory.createEmptyBorder(10, 10, 10, 10)
                    ));
                    productPanel.setBackground(new Color(240, 240, 240));

                    JLabel customerText = new JLabel("Customer: " + customerBackend.getName(currrentOrder.getCustomerId()));
                    JLabel statusText = new JLabel();
                    JLabel orderIdText = new JLabel("Order ID: " + currrentOrder.getOrderId());
                    
                    if(currrentOrder.getOrderStatus().equals("serving"))
                    {
                        statusText.setText("order is " + currrentOrder.getOrderStatus());
                        statusText.setForeground(Color.orange);
                    }
                    else
                    {
                        statusText.setText("order is ready " + currrentOrder.getOrderStatus());
                        statusText.setForeground(Color.blue);
                    }
                    
                    

                    Font textFont = new Font("Arial", Font.PLAIN, 14);
                    customerText.setFont(textFont);
                    orderIdText.setFont(new Font("Arial", Font.PLAIN, 13));
                    statusText.setFont(new Font("Arial", Font.BOLD, 15));

                    JButton toClaim = new JButton("to claim");
                    JButton completed = new JButton("completed");

                    toClaim.setPreferredSize(new Dimension(220, 30));
                    completed.setPreferredSize(new Dimension(220, 30));

                    toClaim.setBackground(new Color(100, 200, 100));
                    completed.setBackground(new Color(100, 100, 200));
                    toClaim.setForeground(Color.WHITE);
                    completed.setForeground(Color.WHITE);
                    toClaim.setBorderPainted(false);
                    completed.setBorderPainted(false);
                    toClaim.setOpaque(true);
                    
                    productPanel.add(statusText);
                    productPanel.add(customerText);
                  
                    productPanel.add(orderIdText);

                    orderContainer.add(productPanel);
                }

                orderContainer.revalidate(); // Refresh layout
                orderContainer.repaint();    // Redraw UI
            });

        }, 0, 5, TimeUnit.SECONDS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout orderContainerLayout = new javax.swing.GroupLayout(orderContainer);
        orderContainer.setLayout(orderContainerLayout);
        orderContainerLayout.setHorizontalGroup(
            orderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        orderContainerLayout.setVerticalGroup(
            orderContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(orderContainer);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("CUSTOMER ORDERS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel orderContainer;
    // End of variables declaration//GEN-END:variables
}
